- name: Generate artifact, copy artifact & sql file to files directory
  hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: Install jdk, maven, git
      dnf:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - java-11-amazon-corretto   # Ubuntu 24.04 default JDK is 11+
        - maven

    - name: Clone source code from GitHub
      git:
        repo: 'https://github.com/devopshydclub/vprofile-project.git'
        dest: ./Vprofile-repo
        version: vp-rem
        force: yes
      register: git_status

    - name: Run mvn install to build artifact
      command: mvn install
      args:
        chdir: Vprofile-repo
      when: git_status.changed
      register: mvn_info

    - name: Ensure files directory exists
      file:
        path: files
        state: directory
        mode: '0755'

    - name: Copy WAR artifact to files directory
      copy:
        src: "{{ item }}"
        dest: files/ROOT.war
        remote_src: yes
      with_fileglob:
        - Vprofile-repo/target/*.war

    - name: Copy SQL file to files directory
      copy:
        src: Vprofile-repo/src/main/resources/db_backup.sql
        dest: files/db_backup.sql
        remote_src: yes
