---
- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  become: yes
  gather_facts: yes

  tasks:

    - name: Print detected OS info
      debug:
        msg: "OS is {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"

    - name: Ensure APT cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg
        - software-properties-common
        - apt-transport-https
        - ca-certificates

    # 🔑 Add Erlang Solutions repo
    - name: Add Erlang Solutions public key
      get_url:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        dest: /usr/share/keyrings/erlang-keyring.gpg
        mode: '0644'

    - name: Add Erlang Solutions APT repository (use jammy for noble)
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/erlang-keyring.gpg] https://packages.erlang-solutions.com/ubuntu jammy contrib"
        filename: erlang
        state: present
        update_cache: yes

    # 🔑 Add RabbitMQ repo
    - name: Add RabbitMQ official public key
      get_url:
        url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.key
        dest: /usr/share/keyrings/rabbitmq-archive-keyring.gpg
        mode: '0644'

    - name: Add RabbitMQ APT repository (use jammy for noble)
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/rabbitmq-archive-keyring.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu jammy main"
        filename: rabbitmq
        state: present
        update_cache: yes

    - name: Update apt cache (fallback)
      shell: apt-get update
      register: apt_output
      retries: 3
      delay: 5
      until: apt_output.rc == 0

    - name: Install Erlang from ESL repo
      apt:
        name: erlang
        state: present
      register: erlang_result
      retries: 3
      delay: 10
      until: erlang_result is succeeded

    - name: Install RabbitMQ Server
      apt:
        name: rabbitmq-server
        state: present
      register: rabbitmq_result
      retries: 3
      delay: 10
      until: rabbitmq_result is succeeded

    - name: Ensure RabbitMQ is started and enabled
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Configure RabbitMQ (disable loopback-only)
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify: Restart RabbitMQ

    - name: Create RabbitMQ user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags:
          - administrator
        state: present
      notify: Restart RabbitMQ

    - name: Enable management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify: Restart RabbitMQ

  handlers:
    - name: Restart RabbitMQ
      service:
        name: rabbitmq-server
        state: restarted
