---
- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  become: yes
  tasks:
    - name: Update apt cache (clear and refresh)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Add Erlang solutions repo key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present

    - name: Add RabbitMQ signing key
      apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
        state: present

    - name: Add RabbitMQ and Erlang apt repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - "deb https://packages.erlang-solutions.com/ubuntu jammy contrib"
        - "deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu jammy main"

    - name: Refresh apt cache
      apt:
        update_cache: yes

    - name: Install Erlang & RabbitMQ
      apt:
        name:
          - erlang
          - rabbitmq-server
        state: present

    - name: Start & enable RabbitMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Configure RabbitMQ (disable loopback-only)
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify: Restart RabbitMQ

    - name: Create RabbitMQ user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags:
          - administrator
        state: present
      notify: Restart RabbitMQ

    - name: Enable management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify: Restart RabbitMQ

  handlers:
    - name: Restart RabbitMQ
      service:
        name: rabbitmq-server
        state: restarted
