- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  become: yes

  tasks:
    - name: Update apt cache (clear and refresh)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Download Erlang public key
      get_url:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        dest: /tmp/erlang_solutions.asc

    - name: Convert Erlang key to keyring format
      command: gpg --dearmor -o /usr/share/keyrings/erlang-keyring.gpg /tmp/erlang_solutions.asc
      args:
        creates: /usr/share/keyrings/erlang-keyring.gpg

    - name: Download RabbitMQ public key
      get_url:
        url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.key
        dest: /tmp/rabbitmq.gpg.key

    - name: Convert RabbitMQ key to keyring format
      command: gpg --dearmor -o /usr/share/keyrings/rabbitmq-archive-keyring.gpg /tmp/rabbitmq.gpg.key
      args:
        creates: /usr/share/keyrings/rabbitmq-archive-keyring.gpg

    - name: Add Erlang APT repository (using Jammy for Noble)
      lineinfile:
        path: /etc/apt/sources.list.d/erlang.list
        line: "deb [signed-by=/usr/share/keyrings/erlang-keyring.gpg] https://packages.erlang-solutions.com/ubuntu jammy contrib"
        create: yes

    - name: Add RabbitMQ APT repository (using Jammy for Noble)
      lineinfile:
        path: /etc/apt/sources.list.d/rabbitmq.list
        line: "deb [signed-by=/usr/share/keyrings/rabbitmq-archive-keyring.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu jammy main"
        create: yes

    - name: Clean up APT lists to avoid lock issues
      file:
        path: /var/lib/apt/lists/lock
        state: absent


    - name: Refresh apt cache with retries
      apt:
        update_cache: yes
      register: apt_update
      retries: 3
      delay: 5
      until: apt_update is succeeded

    - name: Install Erlang & RabbitMQ with retry
      apt:
        name:
          - erlang
          - rabbitmq-server
        state: present
      register: install_output
      retries: 3
      delay: 10
      until: install_output is succeeded

    - name: Start & enable RabbitMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Configure RabbitMQ (disable loopback-only)
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify: Restart RabbitMQ

    - name: Create RabbitMQ user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags:
          - administrator
        state: present
      notify: Restart RabbitMQ

    - name: Enable management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify: Restart RabbitMQ

  handlers:
    - name: Restart RabbitMQ
      service:
        name: rabbitmq-server
        state: restarted
