---
- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  become: yes
  tasks:
    - name: Update apt cache (clear and refresh)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Download Erlang public key
      get_url:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        dest: /tmp/erlang_solutions.asc

    - name: Convert Erlang key to keyring format
      command: gpg --dearmor -o /usr/share/keyrings/erlang-keyring.gpg /tmp/erlang_solutions.asc
      args:
        creates: /usr/share/keyrings/erlang-keyring.gpg

    - name: Add RabbitMQ key (Cloudsmith key)
       get_url:
        url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.key
        dest: /tmp/rabbitmq.gpg.key

    - name: Convert RabbitMQ key to keyring format
      command: gpg --dearmor -o /usr/share/keyrings/rabbitmq-archive-keyring.gpg /tmp/rabbitmq.gpg.key
      args:
        creates: /usr/share/keyrings/rabbitmq-archive-keyring.gpg

          


    - name: Add Erlang APT repository (force jammy for noble)
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/erlang-keyring.gpg] https://packages.erlang-solutions.com/ubuntu jammy contrib"
        filename: "erlang"
        state: present

    - name: Add RabbitMQ APT repository (force jammy for noble)
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/rabbitmq-archive-keyring.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu jammy main"
        filename: "rabbitmq"
        state: present

    - name: Refresh apt cache
      apt:
        update_cache: yes

    - name: Install Erlang & RabbitMQ
      apt:
        name:
          - erlang
          - rabbitmq-server
        state: present

    - name: Start & enable RabbitMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Configure RabbitMQ (disable loopback-only)
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify: Restart RabbitMQ

    - name: Create RabbitMQ user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags:
          - administrator
        state: present
      notify: Restart RabbitMQ

    - name: Enable management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify: Restart RabbitMQ

  handlers:
    - name: Restart RabbitMQ
      service:
        name: rabbitmq-server
        state: restarted
